language: php
sudo: required
dist: trusty
group: edge

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - hhvm # on Trusty only
  - nightly

sudo: false

services:
  - mysql

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest

script: vendor/bin/phpunit --coverage-text
